name: Fantasy LaLiga V3.3

on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      - name: Ejecutar actualización y V3.3
        run: |
          python src/actualizar_y_ejecutar_v3_3.py
